language: node_js

os:
  - linux
  - windows
node_js:
  - 12
  - 14
# https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336/2
env:
  - YARN_GPG=no
workspaces:
  use: shared

install: skip

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_NODE_VERSION" = "12" ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_NODE_VERSION" = "12" ]; then chmod +x ./cc-test-reporter ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_NODE_VERSION" = "12" ]; then ./cc-test-reporter before-build ; fi

script:
  - yarn test:report

after_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_NODE_VERSION" = "12" ]; then ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_NODE_VERSION" = "12" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT ; fi

jobs:
  include:
    - stage: build
      node_js: 14
      install:
        - yarn
      script:
        - yarn build
      # https://docs.travis-ci.com/user/using-workspaces/
      workspaces:
        create:
          name: shared
          paths:
            - node_modules
            - target
            - flow-typed
            - typings
            - docs
    - stage: test
    - stage: release
      node_js: 14
      workspaces:
        use: shared
      before_script: skip
      script:
        - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn release ; fi
      after_script: skip
      install: skip
